In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\sudee\Downloads\revenue_profit_cost_efficiency_dataset.csv")
df

,Date,Region,Product,Category,Revenue,COGS,Operating_Cost,Marketing_Cost,Total_Cost,Profit,Profit_Margin_%
0,2023-01-01,East,Product C,Furniture,7708,13383,3772,4595,21750,-14042,-182.17
1,2023-01-02,West,Product A,Office Supplies,16694,18378,4726,2779,25883,-9189,-55.04
2,2023-01-03,North,Product A,Electronics,14524,24737,8232,1288,34257,-19733,-135.86
3,2023-01-04,East,Product D,Electronics,36880,4353,12339,7951,24643,12237,33.18
4,2023-01-05,East,Product C,Electronics,44224,25821,13281,1214,40316,3908,8.84
...,...,...,...,...,...,...,...,...,...,...,...
495,2024-05-10,East,Product A,Office Supplies,12491,3367,7172,2037,12576,-85,-0.68
496,2024-05-11,East,Product A,Furniture,19859,10189,10312,6665,27166,-7307,-36.79
497,2024-05-12,West,Product D,Office Supplies,13073,11013,8177,7779,26969,-13896,-106.30
498,2024-05-13,North,Product D,Office Supplies,14077,18838,9433,5676,33947,-19870,-141.15
499,2024-05-14,West,Product C,Office Supplies,25953,28200,4897,3637,36734,-10781,-41.54

In [4]:
df.head()

,Date,Region,Product,Category,Revenue,COGS,Operating_Cost,Marketing_Cost,Total_Cost,Profit,Profit_Margin_%
0,2023-01-01,East,Product C,Furniture,7708,13383,3772,4595,21750,-14042,-182.17
1,2023-01-02,West,Product A,Office Supplies,16694,18378,4726,2779,25883,-9189,-55.04
2,2023-01-03,North,Product A,Electronics,14524,24737,8232,1288,34257,-19733,-135.86
3,2023-01-04,East,Product D,Electronics,36880,4353,12339,7951,24643,12237,33.18
4,2023-01-05,East,Product C,Electronics,44224,25821,13281,1214,40316,3908,8.84

In [5]:
df.columns

Index(['Date', 'Region', 'Product', 'Category', 'Revenue', 'COGS',
       'Operating_Cost', 'Marketing_Cost', 'Total_Cost', 'Profit',
       'Profit_Margin_%'],
      dtype='object')

In [6]:
df.shape

(500, 11)

In [40]:
# Created column by Revenue & Total cost
df['Calculated_Profit']=df['Revenue']-df['Total_Cost']
df

,Date,Region,Product,Category,Revenue,COGS,Operating_Cost,Marketing_Cost,Total_Cost,Profit,Profit_Margin_%,Calculated_Profit,Calculated_Profit_Margin_%
0,2023-01-01,East,Product C,Furniture,7708,13383,3772,4595,21750,-14042,-182.17,-14042,-182.174364
1,2023-01-02,West,Product A,Office Supplies,16694,18378,4726,2779,25883,-9189,-55.04,-9189,-55.043728
2,2023-01-03,North,Product A,Electronics,14524,24737,8232,1288,34257,-19733,-135.86,-19733,-135.864776
3,2023-01-04,East,Product D,Electronics,36880,4353,12339,7951,24643,12237,33.18,12237,33.180586
4,2023-01-05,East,Product C,Electronics,44224,25821,13281,1214,40316,3908,8.84,3908,8.836831
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2024-05-10,East,Product A,Office Supplies,12491,3367,7172,2037,12576,-85,-0.68,-85,-0.680490
496,2024-05-11,East,Product A,Furniture,19859,10189,10312,6665,27166,-7307,-36.79,-7307,-36.794401
497,2024-05-12,West,Product D,Office Supplies,13073,11013,8177,7779,26969,-13896,-106.30,-13896,-106.295418
498,2024-05-13,North,Product D,Office Supplies,14077,18838,9433,5676,33947,-19870,-141.15,-19870,-141.152234
499,2024-05-14,West,Product C,Office Supplies,25953,28200,4897,3637,36734,-10781,-41.54,-10781,-41.540477

In [39]:
# checked if Profit is matched with created column
(df['Profit']==df['Calculated_Profit']).value_counts()

True    500
Name: count, dtype: int64

In [41]:
# Created column by Profit & Revenue
df['Calculated_Profit_Margin_%']=(df['Profit']/df['Revenue'])*100
df

,Date,Region,Product,Category,Revenue,COGS,Operating_Cost,Marketing_Cost,Total_Cost,Profit,Profit_Margin_%,Calculated_Profit,Calculated_Profit_Margin_%
0,2023-01-01,East,Product C,Furniture,7708,13383,3772,4595,21750,-14042,-182.17,-14042,-182.174364
1,2023-01-02,West,Product A,Office Supplies,16694,18378,4726,2779,25883,-9189,-55.04,-9189,-55.043728
2,2023-01-03,North,Product A,Electronics,14524,24737,8232,1288,34257,-19733,-135.86,-19733,-135.864776
3,2023-01-04,East,Product D,Electronics,36880,4353,12339,7951,24643,12237,33.18,12237,33.180586
4,2023-01-05,East,Product C,Electronics,44224,25821,13281,1214,40316,3908,8.84,3908,8.836831
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2024-05-10,East,Product A,Office Supplies,12491,3367,7172,2037,12576,-85,-0.68,-85,-0.680490
496,2024-05-11,East,Product A,Furniture,19859,10189,10312,6665,27166,-7307,-36.79,-7307,-36.794401
497,2024-05-12,West,Product D,Office Supplies,13073,11013,8177,7779,26969,-13896,-106.30,-13896,-106.295418
498,2024-05-13,North,Product D,Office Supplies,14077,18838,9433,5676,33947,-19870,-141.15,-19870,-141.152234
499,2024-05-14,West,Product C,Office Supplies,25953,28200,4897,3637,36734,-10781,-41.54,-10781,-41.540477

In [21]:
# Aggregate Revenue & Profit by Product
product_summary=df.groupby('Product')[['Revenue','Profit']].sum()
product_summary

           Revenue  Profit
Product
Product A  3717005  -40466
Product B  3189413 -379388
Product C  3040077 -128603
Product D  3675323  -48604

In [24]:
# Add Profit Margin at Product Level
product_summary['Profit_Margin_%']=(product_summary['Profit']/product_summary['Revenue'])*100
product_summary

           Revenue  Profit  Profit_Margin_%
Product
Product A  3717005  -40466        -1.088672
Product B  3189413 -379388       -11.895230
Product C  3040077 -128603        -4.230255
Product D  3675323  -48604        -1.322442

In [26]:
# Identify High-Revenue, Low-Profit Products
product_summary.sort_values(['Revenue','Profit'],ascending=[False,True])

           Revenue  Profit  Profit_Margin_%
Product
Product A  3717005  -40466        -1.088672
Product D  3675323  -48604        -1.322442
Product B  3189413 -379388       -11.895230
Product C  3040077 -128603        -4.230255

In [29]:
# Aggregate costs by product
cost_summary=df.groupby('Product')[['COGS','Operating_Cost','Marketing_Cost','Total_Cost','Revenue']].sum()
cost_summary

              COGS  Operating_Cost  Marketing_Cost  Total_Cost  Revenue
Product
Product A  2102984         1113708          540779     3757471  3717005
Product B  2012595         1012777          543429     3568801  3189413
Product C  1847543          889275          431862     3168680  3040077
Product D  2038171         1117670          568086     3723927  3675323

In [34]:
# Convert costs into percentages
cost_summary['COGS%']=(cost_summary['COGS']/cost_summary['Revenue'])*100
cost_summary['Operating_Cost%']=(cost_summary['Operating_Cost']/cost_summary['Revenue'])*100
cost_summary['Marketing_Cost_%']=(cost_summary['Marketing_Cost']/cost_summary['Revenue'])*100
cost_summary

,COGS,Operating_Cost,Marketing_Cost,Total_Cost,Revenue,COGS%,Operating_Cost%,Marketing_Cost_%
Product,,,,,,,,
Product A,2102984,1113708,540779,3757471,3717005,56.577379,29.962510,14.548783
Product B,2012595,1012777,543429,3568801,3189413,63.102364,31.754338,17.038527
Product C,1847543,889275,431862,3168680,3040077,60.772901,29.251726,14.205627
Product D,2038171,1117670,568086,3723927,3675323,55.455561,30.410116,15.456764

In [36]:
# Aggregate revenue & profit by region
region_summary=df.groupby('Region')[['Revenue','Profit']].sum()
region_summary

        Revenue  Profit
Region
East    3394754  -53740
North   3237905 -268873
South   2690339 -404204
West    4298820  129756

In [37]:
# Calculate profit margin by region
region_summary['Profit_Margin_%']=(region_summary['Profit']/region_summary['Revenue'])
region_summary

        Revenue  Profit  Profit_Margin_%
Region
East    3394754  -53740        -0.015830
North   3237905 -268873        -0.083039
South   2690339 -404204        -0.150243
West    4298820  129756         0.030184

In [ ]:
df.to_csv('cleaned_revenue_data.csv',index=False)